### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by schongallam** [kenballus/smtp-garden#10]

**Comment by kenballus** [comment]
What does this mean?

**Comment by schongallam** [comment]
Nothing urgent, I just noticed there was no software license even though it
was public.  GPL v3 perhaps? I can delete the issue is you think it's
irrelevant

**Comment by kenballus** [comment]
Oops! Yeah, GPLv3 is my license of choice typically (that's what we use for HTTP Garden). I'll add it.

**Comment by schongallam** [comment]
Done.  I also recommend the Cargo Cult License for future small projects :)
