### ISSUE TITLE
Add msmtp

### ISSUE THREAD

**Issue by schongallam** [kenballus/smtp-garden#14]
Project home page and git link here:
https://marlam.de/msmtp/

**Comment by schongallam** [comment]
msmtp works but requires a workaround.  I could use some help troubleshooting, if anyone has any ideas.  'msmtp' is the container name, and 'msmtpd' is the server executable in the container, and it should listen on container port 25, which docker compose maps to port 2508 on the host.
- If you exec into the container, and run `nc localhost 25`, msmtpd responds like normal and happily sends your email on to echo.
- If you exec into another container like echo, and run `nc msmtp 25`, it refuses the connection.
- If you run `nc localhost 2508` from host, msmtpd is oblivious to the incoming connection.  In msmtpd.c, main(): `listen()` returns fine (line 846) but `accept()` (line 872) never detects the connection.  msmtpd doesn't log anything, because it doesn't detect anything to log.  Even while msmtpd is ignoring an outside connection, `accept()` can still respond to (and properly log) incoming connections from within the container and return a valid file descriptor.

Sounds like a docker config error so far, maybe?

Well, if you swap out smtpd with ncat, or the echo server script, or any other listening activity, it picks up the incoming connection just fine.  So why doesn't smtpd?  I've tried:
- `strace`ing
- switching ports around (both docker mapping and `msmtpd --port=X`)
- confirming it's using IPv4 methods, like the other servers
- "long-syntax" port configuration in the compose yaml (including specifying protocol, app_protocol, etc)
- different invocations of msmtpd

It may be a clue that the connection is refused when you try to connect in from another container on the docker network.  All the other containers accept incoming container-to-container connections just fine.  This is the only indicator that makes me still think this could be a docker configuration issue.  Everything else says "a bug in a library" to me.  I'm out of ideas at this point.

Anyway, the current workaround is to run msmtpd in --inetd mode, and invoke it with `nc -c` (like nullmailer).  This may be ok from a differential testing point of view based on the source code, but it's not ideal.

**Comment by kenballus** [comment]
My guess on this is that it's special-casing localhost; I'm pretty sure at least one of the other containers had a similar behavior a few months ago.

The solution would be to just run evewrything thorugh a TCP proxy (or just nc) on localhost.

**Comment by schongallam** [comment]
Special-casing localhost is exactly the behavior I'm describing, but I can't find the origin of this behavior.  I don't see anything in the msmtpd source code that would make this distinction. Is there some relevant parameter, or behavior, inherent to the libc socket library, that would reflect this?

**Comment by kenballus** [comment]
See [this file](https://git.marlam.de/gitweb/?p=msmtp.git;a=blob_plain;f=src/msmtpd.c;hb=37f811a4139698de17f62dc072524f3275f32526), and look at the global "`DEFAULT_INTERFACE`". I'm assuming this is the root cause. If you change this from 127.0.0.1 to 0.0.0.0, it would probably be able to attach to all interfaces instead of just loopback.

**Comment by schongallam** [comment]
Ah, OK, I see what you are saying. I actually did in fact try running msmtpd with the argument --interface=0.0.0.0, which should've addressed that, and it didn't work.  But I might have been messing with other things, so I'll try again.

**Comment by schongallam** [comment]
Facepalming myself. Of course it works now.

**Comment by schongallam** [comment]
Update tested and pushed.
