### ISSUE TITLE
echo-aio vs synchronous

### ISSUE THREAD

**Issue by schongallam** [kenballus/smtp-garden#16]
Ben-
Reflecting on your comments last night about echo server, and being asynchronous or not.  (And finally recalling the scalability scenarios for which I wrote the async version in the first place)

Would it be helpful to have two docker image versions of echo: one with the original-ish synchronous script, and one with async methods?

**Pro-async (or keeping as-is)**: It seems to currently work fine now, so "if it ain't broke, don't fix it."  Also if we ever want to do high-volume parallel fuzzing (kinda sorta like how t-reqs can do, though, I realize that's a totally different use case), scalability will be necessary.

**Pro-sync**: Simpler, and perhaps more stable?

I lean towards keeping it as is, but I'd welcome re-adding a regular old synchronous version along side it (It would need minimum 4-byte response for nullmailer* compatibility).  I would prefer not to eliminate async echo entirely, though.

Thoughts?

_*or maybe it was msmtp, can't remember_

**Comment by kenballus** [comment]
We should have a conversation about T-Reqs at some point :)

I just prefer whatever is simpler. Probably, there will be no functional differences between aio vs. threads. I vote we leave things as-is, and at some unspecified point in the future, I may feel compelled to rewrite it and we can reconsider then.

**Comment by schongallam** [comment]
As-is, for now, then.  Yes I would like to hear your thoughts on t-reqs soon :)
