### ISSUE TITLE
Add Dovecot

### ISSUE THREAD

**Issue by kenballus** [kenballus/smtp-garden#4]
https://www.dovecot.org/

**Comment by schongallam** [comment]
Dovecot does not appear to have SMTP server functionality.  It can receive emails via LMTP, and it can submit mail to an MTA as an SMTP client itself (Mail Submission Agent mode).  But you can't HELO/EHLO to it on port 25 to send it any SMTP commands.  I made a Dockerfile to build dovecot, but I'm not sure how to approach its potential role in the garden.  Does it even have a role?

**Comment by kenballus** [comment]
LMTP should be sufficient; we just need to LHLO instead of EHLO/HELO and the rest is basically the same.

I think we should treat LMTP servers exactly the same as other participants in the Garden.

**Comment by schongallam** [comment]
Added-- See dovecot readme for usage.
