### ISSUE TITLE
Add PHPMailer

### ISSUE THREAD

**Issue by kenballus** [kenballus/smtp-garden#7]
This is what OpenEMR uses

**Comment by schongallam** [comment]
I'll try to take on this one

**Comment by schongallam** [comment]
After our conversation today, and after further examination of the OpenEMR - PHPMailer code, I'm going to table this in favor of higher yield issues.  Future work might include exploring SMTP smuggling through user freetext entry fields in OpenEMR.

The "email prescription" feature seems to be one of the few ways to reasonably put a long, malicious string into an outgoing email.  Interestingly, this feature had supporting code in the code base, but it was broken by a code refactoring error over 10 years ago (see: [](https://github.com/openemr/openemr/issues/7480)).  As of just a few days ago, there is a pull request to openemr:master to re-enable this! ([](https://github.com/openemr/openemr/pull/7495)) 

Theory of abuse:
1. Assign a malicious string to $Prescription->note (i.e., Patient record -> Prescription -> Edit -> Add -> 'Notes' field.  It kept the first ~64kb of random text, for reference)
2. Generate an inline-html email via C_Prescription::email_prescription().  Functionality for this is in [re-]development.
3. Profit

None of this would imply a flaw in OpenEMR, IMHO -- it should not be OpenEMR's responsibility to screen the content of $note for all possible malicious content, nor would that be practical to implement.  Rather, it should be the responsibility of the receiving mail server to make sure incoming data is parsed correctly.

**Comment by schongallam** [comment]
I'm tabling, due to PHPMailer being a simple SMTP client library and not an SMTP server or MTA.  It could be used for sending SMTP smuggling requests with PHP, however.
